package sega.lexer;

public enum TokenType {
	TKN_NUMBER, TKN_OPERATOR, TKN_AT, TKN_EQUALS, 
	TKN_ID, TKN_QUOTE, TKN_OPEN_BRACKET, TKN_CLOSE_BRACKET, 
	TKN_GTE, TKN_LTE, TKN_GT, TKN_LT, TKN_REAL, TKN_SLASH, TKN_DOT, TKN_PLUS, TKN_MINUS, TKN_DIV, TKN_OPEN_PARENTHESIS, TKN_CLOSE_PARENTHESIS, TKN_STAR, TKN_A, TKN_B, TKN_C
}
